export const BOOKS = {
  id: 'id',
  sourceId: 'source_id',
  type: 'type',
  namespaceId: 'namespace_id',
  name: 'name',
  slug: 'slug',
  author: 'author',
  language: 'lang',
  langAvailable: 'lang_available',
  priceRegular: 'price_regular',
  priceDiscount: 'price_discount',
  publication: 'publication',
  publicationYear: 'publication_year',
  description: 'description',
  images: 'images',
} as const;
